events {}

http {
  server {
    listen 80;
    server_name _;

    location /api/ {
      proxy_pass http://backend:8000/;
    }

    location /poo_phpmyadmin/ {
      proxy_pass http://phpmyadmin:80/;
    }

    location / {
      proxy_pass http://frontend:4173/;
    }
  }
}